Rails.application.routes.draw do
  # Routes for the User resource:
  # CREATE
  get '/new_user' => 'users#new'
  get '/create_user' => 'users#create'

  # READ
  get '/users' => 'users#index'
  get '/users/:id' => 'users#show'

  # UPDATE
  get '/users/:id/edit' => 'users#edit'
  get '/users/:id/update' => 'users#update'

  # DELETE
  get '/users/:id/destroy' => 'users#destroy'
  root 'application#landing'
  get '/index_sched' => 'application#index'
  get '/landing' => 'application#landing'
  get '/new_sched' => 'application#new'
  get '/create' => 'application#create'
  get '/new_roster' => 'application#new_roster'
  get '/edit_roster' => 'application#edit_roster'
  get '/create_roster' => 'application#create_roster'
  get '/index_roster' => 'application#index_roster'
  get '/roster/:id' => 'application#show_roster'
  get '/schedule/:id' => 'application#show'
  get '/roster/:id/edit' => 'application#edit_roster'
  get '/roster/:id/update' => 'application#update_roster'
  get '/roster/:id/destroy' => 'application#destroy_roster'
  get '/schedule/:id/edit' => 'application#edit'
  get '/schedule/:id/update' => 'application#update'
  get '/schedule/:id/destroy' => 'application#destroy'
  get '/index_video' => 'application#index_video'
  get '/video/:id/edit' => 'application#edit_video'
  get '/video/:id/update' => 'application#update_video'
  get '/video/:id/destroy' => 'application#destroy_video'
  get '/new_video' => 'application#new_video'
  get '/create_video' => 'application#create_video'
  get '/plocopa' => 'application#plocopa'
  get '/newpainput1' => 'application#newpainput1'
  get '/newpainput1' => 'application#newpainput1'
  get '/newpainput2' => 'application#newpainput2'
  get '/newpainput3' => 'application#newpainput3'
  get '/newpainput4' => 'application#newpainput4'
  get '/newpainput5' => 'application#newpainput5'
  get '/newpainput6' => 'application#newpainput6'
  get '/newpainput7' => 'application#newpainput7'
  get '/newpainput8' => 'application#newpainput8'
  get '/newpainput9' => 'application#newpainput9'
  get '/newpainput10' => 'application#newpainput10'
  get '/newpainput11' => 'application#newpainput11'
  get '/newpainput12' => 'application#newpainput12'
  get '/newpainput13' => 'application#newpainput13'
  get '/newpainput14' => 'application#newpainput14'
  get '/newpainput15' => 'application#newpainput15'
  get '/newpainput16' => 'application#newpainput16'
  get '/newpainput17' => 'application#newpainput17'
  get '/newpainput18' => 'application#newpainput18'
  get '/newpainput19' => 'application#newpainput19'
  get '/newpainput20' => 'application#newpainput20'
  get '/newpainput21' => 'application#newpainput21'
  get '/newpainput22' => 'application#newpainput22'
  get '/newpainput23' => 'application#newpainput23'
  get '/newpainput24' => 'application#newpainput24'
  get '/newpainput25' => 'application#newpainput25'
  get '/advstat1' => 'application#advstat1'
  get '/advstat2' => 'application#advstat2'
  get '/advstat3' => 'application#advstat3'
  get '/advstat4' => 'application#advstat4'
  get '/advstat5' => 'application#advstat5'
  get '/advstat6' => 'application#advstat6'
  get '/advstat7' => 'application#advstat7'
  get '/advstat8' => 'application#advstat8'
  get '/advstat9' => 'application#advstat9'
  get '/advstat10' => 'application#advstat10'
  get '/advstat11' => 'application#advstat11'
  get '/advstat12' => 'application#advstat12'
  get '/advstat13' => 'application#advstat13'
  get '/advstat14' => 'application#advstat14'
  get '/advstat15' => 'application#advstat15'
  get '/advstat16' => 'application#advstat16'
  get '/advstat17' => 'application#advstat17'
  get '/advstat18' => 'application#advstat18'
  get '/advstat19' => 'application#advstat19'
  get '/advstat20' => 'application#advstat20'
  get '/advstat21' => 'application#advstat21'
  get '/advstat22' => 'application#advstat22'
  get '/advstat23' => 'application#advstat23'
  get '/advstat24' => 'application#advstat24'
  get '/advstat25' => 'application#advstat25'
  get '/index_sched_update' => 'application#index_sched_update'
  get '/index_sched_delete' => 'application#index_sched_delete'
end
